services:
  db:
    container_name: db
    image: postgres:15.4-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy

  ui:
    container_name: ui
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://api:8080/api
    depends_on:
      - api
    networks:
      - app_network

volumes:
  pgdata: {}

networks:
  app_network:
    driver: bridge
