services:
  api:
    container_name: api
    image: api:latest
    build: .
    environment:
      - DATABASE_URL=host=db user=postgres password=postgres dbname=postgres sslmode=disable
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}