import { bookCategory } from "@/types/book";

export const BOOK_CATEGORIES = [
  { value: 'fiction', label: "Fiction" },
  { value: 'non-fiction', label: "Non-Fiction" },
  { value: 'science', label: "Science" },
  { value: 'history', label: "History" },
  { value: 'fantasy', label: "Fantasy" },
  { value: 'mystery', label: "Mystery" },
  { value: 'biography', label: "Biography" },
  { value: 'romance', label: "Romance" },
  { value: 'thriller', label: "Thriller" },
  { value: 'self-help', label: "Self Help" },
  { value: 'cooking', label: "Cooking" },
  { value: 'travel', label: "Travel" },
  { value: 'classics', label: "Classics" },
  { value: 'comics', label: "Comics" }
];

export const MOCK_BOOKS_DATA = [
  {
    id: "1",
    title: "The Great Gatsby",
    authorName: "F. Scott Fitzgerald",
    description:
      "A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 1925,
    rating: 4.2,
    pages: 180,
    isbn: "978-0-7432-7356-5",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    authorName: "Harper Lee",
    description: "A gripping tale of racial injustice and childhood innocence in the American South.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 1960,
    rating: 4.5,
    pages: 324,
    isbn: "978-0-06-112008-4",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    title: "Sapiens: A Brief History of Humankind",
    authorName: "Yuval Noah Harari",
    description:
      "An exploration of how Homo sapiens came to dominate the world through cognitive, agricultural, and scientific revolutions.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 2011,
    rating: 4.4,
    pages: 443,
    isbn: "978-0-06-231609-7",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    title: "The Pragmatic Programmer",
    authorName: "David Thomas, Andrew Hunt",
    description: "A guide to becoming a better programmer through practical advice and timeless principles.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 1999,
    rating: 4.3,
    pages: 352,
    isbn: "978-0-201-61622-4",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "5",
    title: "Dune",
    authorName: "Frank Herbert",
    description:
      "An epic science fiction novel set on the desert planet Arrakis, following Paul Atreides and his journey.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 1965,
    rating: 4.6,
    pages: 688,
    isbn: "978-0-441-17271-9",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "6",
    title: "The Midnight Library",
    authorName: "Matt Haig",
    description:
      "A philosophical novel about life, regret, and the infinite possibilities that exist between life and death.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 2020,
    rating: 4.1,
    pages: 288,
    isbn: "978-0-525-55948-1",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "7",
    title: "Educated",
    authorName: "Tara Westover",
    description: "A powerful memoir about education, family, and the struggle between loyalty and independence.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 2018,
    rating: 4.7,
    pages: 334,
    isbn: "978-0-399-59050-4",
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: "8",
    title: "The Seven Husbands of Evelyn Hugo",
    authorName: "Taylor Jenkins Reid",
    description: "A captivating novel about a reclusive Hollywood icon who finally decides to tell her story.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 2017,
    rating: 4.8,
    pages: 400,
    isbn: "978-1-5011-3981-2",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "9",
    title: "The Great Gatsby",
    authorName: "F. Scott Fitzgerald",
    description:
      "A classic American novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 1925,
    rating: 4.2,
    pages: 180,
    isbn: "978-0-7432-7356-5",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "10",
    title: "To Kill a Mockingbird",
    authorName: "Harper Lee",
    description: "A gripping tale of racial injustice and childhood innocence in the American South.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 1960,
    rating: 4.5,
    pages: 324,
    isbn: "978-0-06-112008-4",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "11",
    title: "Sapiens: A Brief History of Humankind",
    authorName: "Yuval Noah Harari",
    description:
      "An exploration of how Homo sapiens came to dominate the world through cognitive, agricultural, and scientific revolutions.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 2011,
    rating: 4.4,
    pages: 443,
    isbn: "978-0-06-231609-7",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "12",
    title: "The Pragmatic Programmer",
    authorName: "David Thomas, Andrew Hunt",
    description: "A guide to becoming a better programmer through practical advice and timeless principles.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 1999,
    rating: 4.3,
    pages: 352,
    isbn: "978-0-201-61622-4",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "13",
    title: "Dune",
    authorName: "Frank Herbert",
    description:
      "An epic science fiction novel set on the desert planet Arrakis, following Paul Atreides and his journey.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 1965,
    rating: 4.6,
    pages: 688,
    isbn: "978-0-441-17271-9",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "14",
    title: "The Midnight Library",
    authorName: "Matt Haig",
    description:
      "A philosophical novel about life, regret, and the infinite possibilities that exist between life and death.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 2020,
    rating: 4.1,
    pages: 288,
    isbn: "978-0-525-55948-1",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "15",
    title: "Educated",
    authorName: "Tara Westover",
    description: "A powerful memoir about education, family, and the struggle between loyalty and independence.",
    category: bookCategory.FICTION,
    image: "/assets/books/harry-potter.png",
    publicationYear: 2018,
    rating: 4.7,
    pages: 334,
    isbn: "978-0-399-59050-4",
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: "16",
    title: "The Seven Husbands of Evelyn Hugo",
    authorName: "Taylor Jenkins Reid",
    description: "A captivating novel about a reclusive Hollywood icon who finally decides to tell her story.",
    category: bookCategory.FICTION,
    image: "/assets/books/great-gatsby.png",
    publicationYear: 2017,
    rating: 4.8,
    pages: 400,
    isbn: "978-1-5011-3981-2",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
]